/**
 * What's in the pack for the climb, shown on the mountain trail (the pack goes the whole way up).
 * Pieced together from the career, the workshop, the blog and the GitHub repos, so every
 * item has something real behind it (the `proof`).
 */
export interface Pouch {
  name: string;
  items: string[];
  proof: string;
}

export const skills: Pouch[] = [
  {
    name: 'Architecture',
    items: ['Software architecture', 'Modular monoliths', 'Domain-driven design', 'Technical direction'],
    proof: 'Fifteen years of building software, from transport and car sharing to power trading. I lead the architecture of Direct+.',
  },
  {
    name: 'Languages',
    items: ['Kotlin', 'Java', 'Python', 'TypeScript', 'C# (a bit)'],
    proof: 'Kotlin and Java at work and in Argentum, Python for anything with a neural net, TypeScript for the web. Anything else I leave to my AI.',
  },
  {
    name: 'Building the thing',
    items: ['Spring Boot', 'Node.js', 'PostgreSQL', 'MySQL', 'Redis', 'Kafka', 'React', 'Android', 'Three.js', 'Docker', 'Kubernetes', 'AWS', 'GitHub Actions'],
    proof: 'So many full-stack projects that I have touched most of the usual tech at least once: back ends, databases, queues, web clients, mobile apps and the pipelines that ship them. This island runs on Three.js.',
  },
  {
    name: 'AI & machine learning',
    items: ['Agentic engineering', 'LLM apps & agents', 'Neural networks from scratch', 'Transformers from scratch', 'Fine-tuning', 'Reinforcement learning', 'Image generation', 'Music generation'],
    proof: 'I started by learning how neural networks work from scratch: DQN and MuZero, a language model of my own, a song for the AI Song Contest. These days I am a certified vibe coder with a lot of agentic engineering behind me: whole Magic sets generated by AI, and Talespinner.',
  },
  {
    name: 'Games',
    items: ['Rules engines', 'Game AI', 'Godot', 'Procedural worlds'],
    proof: 'The big one is Argentum, a full Magic: The Gathering rules engine with an AI to play against. Around it, smaller projects and prototypes, mostly to gather knowledge and experience: Carcassonne, a racing game through Google Maps 3D tiles, a top-down flying game, and the start of a metroidvania. Not much of an artist (yet).',
  },
  {
    name: 'Know-how',
    items: ['Energy trading', 'Route planning', 'Public transport', 'Car sharing'],
    proof: 'The fields I have worked in.',
  },
];
