/**
 * What's in the pack for the climb, shown on the mountain trail (the pack goes the whole way up).
 * Pieced together from the career, the workshop, the blog and the GitHub repos, so every
 * item has something real behind it (the `proof`).
 */
export interface Pouch {
  name: string;
  items: string[];
  proof: string;
}

export const skills: Pouch[] = [
  {
    name: 'Architecture & leading',
    items: ['Software architecture', 'Modular monoliths', 'Domain-driven design', 'Technical direction', 'Teaching'],
    proof: 'Fifteen years of building software, from transport and car sharing to power trading. I lead the architecture of Direct+, and I once taught a whole team to program.',
  },
  {
    name: 'Languages',
    items: ['Kotlin', 'Java', 'Python', 'TypeScript', 'C# (a bit)'],
    proof: 'Kotlin and Java at work and in Argentum, Python for anything with a neural net, TypeScript for the web. Anything else I leave to my AI.',
  },
  {
    name: 'Building the thing',
    items: ['Spring Boot', 'PostgreSQL', 'React', 'Android', 'Three.js', 'Docker', 'GitHub Actions'],
    proof: 'Back ends, web clients and mobile apps, shipped and kept running. This island runs on Three.js.',
  },
  {
    name: 'AI & machine learning',
    items: ['LLM apps & agents', 'Transformers from scratch', 'Fine-tuning', 'Reinforcement learning', 'Image generation', 'Music generation', 'Building with AI'],
    proof: 'Ten years of it: DQN and MuZero, a language model built from scratch, a song for the AI Song Contest, whole Magic sets generated by AI, and Talespinner.',
  },
  {
    name: 'Games',
    items: ['Rules engines', 'Game AI', 'Godot', 'Procedural worlds', 'Pixel art', 'Blender'],
    proof: 'Argentum, Carcassonne, a metroidvania in progress, and every model on this island.',
  },
  {
    name: 'Know-how',
    items: ['Energy trading', 'Route planning', 'Public transport', 'Car sharing'],
    proof: 'The fields I have worked in.',
  },
];
